name: Verify Translations

on:
  workflow_call:
    inputs:
      runner:
        description: "The runner to use"
        required: false
        default: 'ubuntu-latest'
        type: string
      renpy_version:
        description: "The version of Ren'Py to use"
        required: false
        default: ""
        type: string
      renpy_dlcs:
        description: "The Ren'Py DLCs to install"
        required: false
        default: ""
        type: string
      languages:
        description: "The supported languages"
        required: false
        default: "None"
        type: string

permissions:
  contents: read

jobs:
  translation_check:
    name: "Translation check"
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: project
      - name: "Prepare Ren'Py cache"
        id: cache-renpy
        uses: actions/cache@v3
        with:
          path: renpy
          key: ${{ runner.os }}-renpy-${{ inputs.renpy_version }}-
      - name: "Install Ren'Py"
        uses: Ayowel/renpy-setup-action@v2
        if: steps.cache-renpy.outputs.cache-hit != 'true'
        with:
          action: install
          version: ${{ inputs.renpy_version }}
          dlc: ${{ inputs.renpy_dlcs }}
          install_dir: renpy
      - name: "Update translations"
        uses: Ayowel/renpy-setup-action@v2
        with:
          action: translate
          install_dir: renpy
          game: project
          languages: ${{ inputs.languages }}
      - name: "Look for translation changes"
        run: |
          [[ -z "$(git status --porcelain)" ]]
        working-directory: project
